### ISSUE TITLE
Request for tagged release 0.69

### ISSUE THREAD

**Issue by FredeHoey** [rbock/sqlpp23#111]
Hi @rbock 

I'm in the process of integrating your library in a yocto project, and I'd like to upstream the recipe I end up with, such that others can benefit from your outstanding library.
For it to be upstreamed, it's preferred to have a tagged version. On 0.68, the tests don't compile with gcc 15.2 but the most recent commit on main does.

Compilation error on 0.68
```
FAILED: [code=1] tests/core/serialize/clause/CMakeFiles/sqlpp23_core_serialize_clause_insert_columns.dir/insert_columns.cpp.o
ccache /workspace/cs-yocto/build/tmp/work/cortexa72-linux/sqlpp23/0.68/recipe-sysroot-native/usr/bin/aarch64-linux/aarch64-linux-g++ --sysroot=/workspace/cs-yocto/build/tmp/work/cortexa72-linux/sqlpp23/0.68/recipe-sysroot  -I/workspace/cs-yocto/build/tmp/work/cortexa72-linux/sqlpp23/0.68/sources/sqlpp23-0.68/include -I/workspace/cs-yocto/build/tmp/work/cortexa72-linux/sqlpp23/0.68/sources/sqlpp23-0.68/tests/include -I/workspace/cs-yocto/build/tmp/work/cortexa72-linux/sqlpp23/0.68/sources/sqlpp23-0.68/tests/core -mcpu=cortex-a72+crc+nocrypto -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/workspace/cs-yocto/build/tmp/work/cortexa72-linux/sqlpp23/0.68/recipe-sysroot  -O2 -g -fcanon-prefix-map  -ffile-prefix-map=/workspace/cs-yocto/build/tmp/work/cortexa72-linux/sqlpp23/0.68/sources/sqlpp23-0.68=/usr/src/debug/sqlpp23/0.68  -ffile-prefix-map=/workspace/cs-yocto/build/tmp/work/cortexa72-linux/sqlpp23/0.68/build=/usr/src/debug/sqlpp23/0.68  -ffile-prefix-map=/workspace/cs-yocto/build/tmp/work/cortexa72-linux/sqlpp23/0.68/recipe-sysroot=  -ffile-prefix-map=/workspace/cs-yocto/build/tmp/work/cortexa72-linux/sqlpp23/0.68/recipe-sysroot-native=  -pipe -fvisibility-inlines-hidden -std=gnu++23 -Wall -Wextra -pedantic -Wshadow -Wconversion -MD -MT tests/core/serialize/clause/CMakeFiles/sqlpp23_core_serialize_clause_insert_columns.dir/insert_columns.cpp.o -MF tests/core/serialize/clause/CMakeFiles/sqlpp23_core_serialize_clause_insert_columns.dir/insert_columns.cpp.o.d -o tests/core/serialize/clause/CMakeFiles/sqlpp23_core_serialize_clause_insert_columns.dir/insert_columns.cpp.o -c /workspace/cs-yocto/build/tmp/work/cortexa72-linux/sqlpp23/0.68/sources/sqlpp23-0.68/tests/core/serialize/clause/insert_columns.cpp
In file included from ../recipe-sysroot/usr/include/c++/15.2.0/format:50,
                 from ../recipe-sysroot/usr/include/c++/15.2.0/ostream:44,
                 from ../recipe-sysroot/usr/include/c++/15.2.0/istream:43,
                 from ../recipe-sysroot/usr/include/c++/15.2.0/sstream:42,
                 from ../recipe-sysroot/usr/include/c++/15.2.0/chrono:51,
                 from ../sources/sqlpp23-0.68/tests/include/sqlpp23/tests/core/all.h:32,
                 from ../sources/sqlpp23-0.68/tests/core/serialize/clause/insert_columns.cpp:27:
../recipe-sysroot/usr/include/c++/15.2.0/type_traits: In substitution of 'template<class _Up>  requires !(is_same_v<std::optional<_Tp>, typename std::remove_cvref<_It2>::type>) && !(is_same_v<std::in_place_t, typename std::remove_cvref<_It2>::type>) && (is_constructible_v<_Tp, _Up>) && (__not_constructing_bool_from_optional<_Up, typename std::remove_cv< <template-parameter-1-1> >::type>) constexpr std::optional<sqlpp::insert_value_t<sqlpp::column_t<sqlpp::table_t<test::TabFoo_>, test::TabFoo_::IntN> > >::optional(_Up&&) [with _Up = sqlpp::dynamic_t<sqlpp::insert_value_t<sqlpp::column_t<sqlpp::table_t<test::TabFoo_>, test::TabFoo_::IntN> > >]':
../recipe-sysroot/usr/include/c++/15.2.0/type_traits:3557:46:   required from 'constexpr const bool std::is_constructible_v<sqlpp::insert_value_t<sqlpp::column_t<sqlpp::table_t<test::TabFoo_>, test::TabFoo_::IntN> >, sqlpp::dynamic_t<sqlpp::insert_value_t<sqlpp::column_t<sqlpp::table_t<test::TabFoo_>, test::TabFoo_::IntN> > > >'
 3557 |   inline constexpr bool is_constructible_v = __is_constructible(_Tp, _Args...);
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../recipe-sysroot/usr/include/c++/15.2.0/optional:871:7:   required by substitution of 'template<class _Up>  requires !(is_same_v<std::optional<_Tp>, typename std::remove_cvref<_It2>::type>) && !(is_same_v<std::in_place_t, typename std::remove_cvref<_It2>::type>) && (is_constructible_v<_Tp, _Up>) && (__not_constructing_bool_from_optional<_Up, typename std::remove_cv< <template-parameter-1-1> >::type>) constexpr std::optional<sqlpp::insert_value_t<sqlpp::column_t<sqlpp::table_t<test::TabFoo_>, test::TabFoo_::IntN> > >::optional(_Up&&) [with _Up = sqlpp::dynamic_t<sqlpp::insert_value_t<sqlpp::column_t<sqlpp::table_t<test::TabFoo_>, test::TabFoo_::IntN> > >]'
  871 |           && is_constructible_v<_Tp, _Up>
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../recipe-sysroot/usr/include/c++/15.2.0/type_traits:1151:25:   required by substitution of 'template<class _Tp, class ... _Args> using std::__is_constructible_impl = std::__bool_constant<__is_constructible(_Tp, _Args ...)> [with _Tp = sqlpp::insert_value_t<sqlpp::column_t<sqlpp::table_t<test::TabFoo_>, test::TabFoo_::IntN> >; _Args = {sqlpp::dynamic_t<sqlpp::insert_value_t<sqlpp::column_t<sqlpp::table_t<test::TabFoo_>, test::TabFoo_::IntN> > >}]'
 1151 |       = __bool_constant<__is_constructible(_Tp, _Args...)>;
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../recipe-sysroot/usr/include/c++/15.2.0/type_traits:1156:12:   required from 'struct std::is_constructible<sqlpp::insert_value_t<sqlpp::column_t<sqlpp::table_t<test::TabFoo_>, test::TabFoo_::IntN> >, sqlpp::dynamic_t<sqlpp::insert_value_t<sqlpp::column_t<sqlpp::table_t<test::TabFoo_>, test::TabFoo_::IntN> > > >'
 1156 |     struct is_constructible
      |            ^~~~~~~~~~~~~~~~
../recipe-sysroot/usr/include/c++/15.2.0/type_traits:188:35:   required by substitution of 'template<class ... _Bn> std::__detail::__first_t<std::integral_constant<bool, true>, typename std::enable_if<(bool)(_Bn::value), void>::type ...> std::__detail::__and_fn(int) [with _Bn = {std::is_constructible<sqlpp::insert_value_t<sqlpp::column_t<sqlpp::table_t<test::TabFoo_>, test::TabFoo_::IntN> >, sqlpp::dynamic_t<sqlpp::insert_value_t<sqlpp::column_t<sqlpp::table_t<test::TabFoo_>, test::TabFoo_::IntN> > > >}]'
  188 |                                       __enable_if_t<bool(_Bn::value)>...>;
      |                                                               ^~~~~
../recipe-sysroot/usr/include/c++/15.2.0/type_traits:204:42:   required from 'struct std::__and_<std::is_constructible<sqlpp::insert_value_t<sqlpp::column_t<sqlpp::table_t<test::TabFoo_>, test::TabFoo_::IntN> >, sqlpp::dynamic_t<sqlpp::insert_value_t<sqlpp::column_t<sqlpp::table_t<test::TabFoo_>, test::TabFoo_::IntN> > > > >'
  204 |     : decltype(__detail::__and_fn<_Bn...>(0))
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
../recipe-sysroot/usr/include/c++/15.2.0/type_traits:219:53:   required from 'constexpr const bool std::__and_v<std::is_constructible<sqlpp::insert_value_t<sqlpp::column_t<sqlpp::table_t<test::TabFoo_>, test::TabFoo_::IntN> >, sqlpp::dynamic_t<sqlpp::insert_value_t<sqlpp::column_t<sqlpp::table_t<test::TabFoo_>, test::TabFoo_::IntN> > > > >'
  219 |     inline constexpr bool __and_v = __and_<_Bn...>::value;
      |                                                     ^~~~~
../recipe-sysroot/usr/include/c++/15.2.0/tuple:843:13:   required from 'static consteval bool std::tuple< <template-parameter-1-1> >::__constructible() [with _UTypes = {sqlpp::dynamic_t<sqlpp::insert_value_t<sqlpp::column_t<sqlpp::table_t<test::TabFoo_>, test::TabFoo_::IntN> > >}; _Elements = {sqlpp::insert_value_t<sqlpp::column_t<sqlpp::table_t<test::TabFoo_>, test::TabFoo_::IntN> >}]'
  843 |             return __and_v<is_constructible<_Elements, _UTypes>...>;
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../recipe-sysroot/usr/include/c++/15.2.0/tuple:980:35:   required by substitution of 'template<class ... _UTypes>  requires  __disambiguating_constraint<_UTypes ...>() && __constructible<_UTypes ...>() && !__dangles<_UTypes ...>() constexpr std::tuple<sqlpp::insert_value_t<sqlpp::column_t<sqlpp::table_t<test::TabFoo_>, test::TabFoo_::IntN> > >::tuple(_UTypes&& ...) [with _UTypes = {sqlpp::dynamic_t<sqlpp::insert_value_t<sqlpp::column_t<sqlpp::table_t<test::TabFoo_>, test::TabFoo_::IntN> > >}]'
  980 |           && (__constructible<_UTypes...>())
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
../sources/sqlpp23-0.68/include/sqlpp23/core/clause/insert_value_list.h:230:3:   required by substitution of 'template<class ... Assignments>  requires ((... && DynamicAssignment<Assignments>)) && ((std::is_same<std::tuple<_Ts ...>, std::tuple<typename sqlpp::lhs<typename sqlpp::remove_dynamic<Assignments>::type>::type ...> >::value) && (CorrectAddValuesAssignments<std::tuple<typename sqlpp::make_insert_value<Columns>::type ...>, Assignments ...>)) void sqlpp::column_list_t<sqlpp::column_t<sqlpp::table_t<test::TabFoo_>, test::TabFoo_::IntN> >::add_values(Assignments ...) [with Assignments = {sqlpp::dynamic_t<sqlpp::assign_expression<sqlpp::column_t<sqlpp::table_t<test::TabFoo_>, test::TabFoo_::IntN>, sqlpp::op_assign, int> >}]'
  230 |   Tuple{make_insert_value_t<lhs_t<Assignments>>(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  231 |       get_rhs(std::move(assignments)))...};
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../sources/sqlpp23-0.68/tests/core/serialize/clause/insert_columns.cpp:46:17:   required from here
   46 |     i.add_values(dynamic(true, foo.intN = 42));
      |     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../recipe-sysroot/usr/include/c++/15.2.0/optional:874:2:   required by the constraints of 'template<class _Tp> template<class _Up>  requires !(is_same_v<std::optional<_Tp>, typename std::remove_cvref<_It2>::type>) && !(is_same_v<std::in_place_t, typename std::remove_cvref<_It2>::type>) && (is_constructible_v<_Tp, _Up>) && (__not_constructing_bool_from_optional<_Up, typename std::remove_cv< <template-parameter-1-1> >::type>) constexpr std::optional<_Tp>::optional(_Up&&)'
../recipe-sysroot/usr/include/c++/15.2.0/optional:871:14: error: satisfaction of atomic constraint 'is_constructible_v<_Tp, _Up> [with _Tp = _Tp; _Up = _Up]' depends on itself
  871 |           && is_constructible_v<_Tp, _Up>
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by rbock** [comment]
Hi @FredeHoey , Thanks for the ping and thanks for your support in spreading the library!

I just tagged the release.

Cheers,
Roland
